## 例外捕捉
- raiseメソッド  
自発的に例外を発生させる
```
raise ZeroDivisionError, "hello, error!"
=>ZeroDivisionError: hello, error!
```

- RuntimeError  
`raise '例外が発生しました'`
=> RuntimeError(例外が発生しました)

```
begin 
    (例外が発生しそうなコード)
rescue
    (例外処理)
ensure
    (必ず行う処理。なくてもよい)
end
```
- メソッド内・・・begin いらない
```
def
    (メソッドのコード)
rescue
    (例外に対応するコード)
ensure
    (例外が発生なくても行う処理)
end
```

---
1. do_somethingメソッドを実行し、
1. 実行中に起こったエラーを自作のSomeSpecialErrorでキャッチする
1. 例外を変数eで受け取り、例外の内容を出力する
```
begin
    do_something
rescue SomeSpecialError => e
   puts "#{e.class}(#{e.message})!!!!!"
end